// Autogenerated from Pigeon (v19.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "CommentsApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface CommentModel ()
+ (CommentModel *)fromList:(NSArray *)list;
+ (nullable CommentModel *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation CommentModel
+ (instancetype)makeWithPostId:(NSInteger )postId
    id:(NSInteger )id
    name:(NSString *)name
    email:(NSString *)email
    body:(NSString *)body {
  CommentModel* pigeonResult = [[CommentModel alloc] init];
  pigeonResult.postId = postId;
  pigeonResult.id = id;
  pigeonResult.name = name;
  pigeonResult.email = email;
  pigeonResult.body = body;
  return pigeonResult;
}
+ (CommentModel *)fromList:(NSArray *)list {
  CommentModel *pigeonResult = [[CommentModel alloc] init];
  pigeonResult.postId = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.id = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.name = GetNullableObjectAtIndex(list, 2);
  pigeonResult.email = GetNullableObjectAtIndex(list, 3);
  pigeonResult.body = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable CommentModel *)nullableFromList:(NSArray *)list {
  return (list) ? [CommentModel fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.postId),
    @(self.id),
    self.name ?: [NSNull null],
    self.email ?: [NSNull null],
    self.body ?: [NSNull null],
  ];
}
@end

@interface CommentsApiCodecReader : FlutterStandardReader
@end
@implementation CommentsApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [CommentModel fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface CommentsApiCodecWriter : FlutterStandardWriter
@end
@implementation CommentsApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[CommentModel class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface CommentsApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation CommentsApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[CommentsApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[CommentsApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *CommentsApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    CommentsApiCodecReaderWriter *readerWriter = [[CommentsApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpCommentsApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CommentsApi> *api) {
  SetUpCommentsApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpCommentsApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CommentsApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pinapp_challenge.CommentsApi.fetchComments", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CommentsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fetchCommentsPostId:completion:)], @"CommentsApi api (%@) doesn't respond to @selector(fetchCommentsPostId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSInteger arg_postId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api fetchCommentsPostId:arg_postId completion:^(NSArray<CommentModel *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
